# Generated by Django 5.2.3 on 2025-06-15 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='name',
            field=models.CharField(default='고준석', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='employee_number',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='tasks.employeenumber'),
        ),
    ]
