# Generated by Django 5.2.3 on 2025-06-15 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_customuser_name_alter_customuser_employee_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='phone',
        ),
    ]
