# Generated by Django 4.2.2 on 2025-06-24 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WBSItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("task_title", models.CharField(max_length=200)),
                ("task_owner", models.CharField(max_length=100)),
                ("device", models.CharField(max_length=100)),
                ("start_date", models.DateField()),
                ("due_date", models.DateField()),
                ("tester", models.CharField(max_length=100)),
                ("duration", models.IntegerField()),
                (
                    "progress",
                    models.CharField(
                        choices=[
                            ("Wait", "Wait"),
                            ("In progress", "In progress"),
                            ("COMPLETE", "COMPLETE"),
                            ("Hold", "Hold"),
                        ],
                        max_length=50,
                    ),
                ),
                ("comment", models.TextField(blank=True)),
            ],
        ),
    ]
