# Generated by Django 4.2.2 on 2025-06-24 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="wbsitem",
            name="no",
            field=models.PositiveIntegerField(default=0, unique=True),
        ),
        migrations.AlterField(
            model_name="wbsitem",
            name="duration",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="wbsitem",
            name="progress",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="wbsitem",
            name="task_title",
            field=models.CharField(max_length=255),
        ),
    ]
