# Generated by Django 4.2.2 on 2025-06-24 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0002_wbsitem_no_alter_wbsitem_duration_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="wbsitem",
            name="no",
        ),
    ]
