# Generated by Django 4.2.2 on 2025-06-24 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0003_remove_wbsitem_no"),
    ]

    operations = [
        migrations.AddField(
            model_name="wbsitem",
            name="no",
            field=models.PositiveIntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
