# Generated by Django 5.2.4 on 2025-07-14 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_wbsitem_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wbsitem',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wbsitem',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
