# Generated by Django 5.2.4 on 2025-07-15 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_alter_wbsitem_due_date_alter_wbsitem_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='wbsitem',
            name='task_content',
            field=models.TextField(blank=True),
        ),
    ]
